### ISSUE TITLE
Should payload field default to empty (0 length Octets) for DATA frames?

### ISSUE THREAD

**Issue by dpwspoon** [reaktivity/nukleus-maven-plugin#36]
Reset or equivilant is still required when you just want to send extensions

```java
            DataFW data = dataRW.wrap(writeBuffer, 0, writeBuffer.capacity())
                .streamId(targetId)
                .payload(e -> e.reset())
                .extension(e -> e.set(visitHttp2PushPromiseEx(mutator)))
                .build();
```

**Comment by dpwspoon** [comment]
If you don't reset you get the exception:

```
java.lang.IllegalStateException: Required field "payload" is not set
	at org.reaktivity.nukleus.http_cache.internal.types.stream.DataFW$Builder.checkFieldsSet(DataFW.java:265)
	at org.reaktivity.nukleus.http_cache.internal.types.stream.DataFW$Builder.extension(DataFW.java:215)
	at org.reaktivity.nukleus.http_cache.internal.types.stream.DataFW$Builder.extension(DataFW.java:220)
	at org.reaktivity.nukleus.http_cache.internal.stream.util.Writer.doH2PushPromise(Writer.java:279)
	at org.reaktivity.nukleus.http_cache.internal.stream.util.Writer.doHttpPushPromise(Writer.java:201)
	at org.reaktivity.nukleus.http_cache.internal.stream.ProxyConnectReplyStream.handleCacheableResponse(ProxyConnectReplyStream.java:113)
	at org.reaktivity.nukleus.http_cache.internal.stream.ProxyConnectReplyStream.handleBegin(ProxyConnectReplyStream.java:88)
	at org.reaktivity.nukleus.http_cache.internal.stream.ProxyConnectReplyStream.beforeBegin(ProxyConnectReplyStream.java:59)
	at org.reaktivity.nukleus.http_cache.internal.stream.ProxyConnectReplyStream.handleStream(ProxyConnectReplyStream.java:47)
	at org.reaktivity.reaktor.internal.acceptable.Source.handleBegin(Source.java:251)
	at org.reaktivity.reaktor.internal.acceptable.Source.handleUnrecognized(Source.java:218)
	at org.reaktivity.reaktor.internal.acceptable.Source.handleRead(Source.java:199)
	at org.agrona.concurrent.ringbuffer.OneToOneRingBuffer.read(OneToOneRingBuffer.java:198)
	at org.agrona.concurrent.ringbuffer.OneToOneRingBuffer.read(OneToOneRingBuffer.java:157)
	at org.reaktivity.reaktor.internal.acceptable.Source.process(Source.java:95)
	at org.reaktivity.nukleus.Nukleus$Composite.process(Nukleus.java:52)
	at org.reaktivity.nukleus.Nukleus$Composite.process(Nukleus.java:52)
	at org.reaktivity.nukleus.Nukleus$Composite.process(Nukleus.java:52)
	at org.reaktivity.reaktor.Reaktor.lambda$supplyWorker$0(Reaktor.java:180)
	at org.reaktivity.reaktor.Reaktor$1.doWork(Reaktor.java:116)
	at org.agrona.concurrent.AgentRunner.run(AgentRunner.java:122)
	at java.lang.Thread.run(Thread.java:745)
	Suppressed: java.lang.Exception: [http-cache/target]	[0x0000000073e2ac30] streams=[tailAt=0x0000000000000078, headAt=0x0000000000000000], throttle=[tailAt=0x0000000000000000, headAt=0x0000000000000000]
		at org.reaktivity.reaktor.internal.acceptable.Source.handleRead(Source.java:204)
		... 10 more

org.junit.ComparisonFailure: Specified behavior did not match expected:<...lidate=100")}

read [nukleus:data.ext ${http:header(":scheme", "http")}
                      ${http:header(":method", "GET")}
                      ${http:header(":path", "/data")}
                      ${http:header(":authority", "localhost:8080")}
                      ${http:header("cache-control", "no-cache")}
                      ${http:header("prefer", "x-on-update, wait=5")}

read "hello world"

read ]closed
#
# Copyright...> but was:<...lidate=100")}

read []closed
#
# Copyright...>
	at org.junit.Assert.assertEquals(Assert.java:115)
	at org.kaazing.k3po.junit.rules.SpecificationStatement.evaluate(SpecificationStatement.java:132)
	at org.junit.rules.Verifier$1.evaluate(Verifier.java:35)
	at org.reaktivity.reaktor.test.ReaktorRule$1.evaluate(ReaktorRule.java:219)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)


```

**Comment by dpwspoon** [comment]
Update on this is you don't need a call to reset, you can do `.payload(e -> {})`, but it would be better if it just defaulted, so leaving this open.

**Comment by jfallows** [comment]
This is really a discussion of the default `DATA` frame `length` field value.

We may need to support `undefined` `DATA` frame payload as differentiated from `empty` `DATA` frame payload, so that `extension` metadata can be communicated without implying an `empty` `DATA` frame.
